### ISSUE TITLE
Use package path/filepath instead of path

### ISSUE THREAD

**Issue by dolmen** [frioux/leatherman#1]
The package [`path`](https://golang.org/pkg/path) is for abstract path using forward slashes.

The package [`path/filepath`](https://golang.org/pkg/path/filepath) is for filesystem paths using O/S dependent separator.

Using `path/filepath` instead of `path` in `leatherman` would improve its portability.

**Comment by frioux** [comment]
Send a PR and I'll accept it!

**Comment by frioux** [comment]
Thanks!
